version: "3"

services:
    convert:
        build:
            context: ./convert
            dockerfile: Dockerfile.dev
        # define volume to enable livereload
        volumes:
            - "./convert:/app"
        # port variables are not received from the env_file below
        # but defined by `docker-compose --env-file <file> up`
        ports:
            - "${CONVERT_PORT}:${CONVERT_PORT}"
        # define environment variables in the built image
        env_file:
            - .env

    storage:
        build:
            context: ./storage
            dockerfile: Dockerfile.dev
        # define volume to enable livereload
        volumes:
            - "./storage:/app"
        # port variables are not received from the env_file below
        # but defined by `docker-compose --env-file <file> up`
        ports:
            - "${STORAGE_PORT}:${STORAGE_PORT}"
        # define environment variables in the built image
        env_file:
            - .env

    website:
        build:
            context: ./website
            dockerfile: Dockerfile.dev
        volumes:
            - "./website:/app"
        ports:
            - "${WEBSITE_PORT}:${WEBSITE_PORT}"
        env_file:
            - .env
        environment:
            DOCKER_COMPOSE: "true"