apiVersion: v1
kind: Service
metadata:
  name: convert
  namespace: {{PROJECT_NAME}}
  labels:
    app: convert
spec:
  selector:
    app: convert
  ports:
  - port: {{CONVERT_PORT}}
    protocol: TCP  
    targetPort: {{CONVERT_PORT}}
