apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: {{PROJECT_NAME}}
  labels:
    app: storage
spec:
  selector:
    app: storage
  ports:
  - port: {{STORAGE_PORT}}
    protocol: TCP  
    targetPort: {{STORAGE_PORT}}
