apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: {{PROJECT_NAME}}
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
  - port: 80
    protocol: TCP  
    targetPort: {{WEBSITE_PORT}}
  type: LoadBalancer
